# Generated by Django 5.2.8 on 2025-12-03 15:36

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_enhancements', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'flac', 'aac', 'm4a'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Album art or cover', null=True, upload_to='audio_thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(blank=True, help_text='Audio duration', null=True)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('copyright_holder', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='audio_files', to='media_enhancements.category')),
                ('collection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='wagtailcore.collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(blank=True, help_text='Video duration', null=True)),
                ('resolution', models.CharField(blank=True, help_text='e.g., 1920x1080', max_length=50)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('producer', models.CharField(blank=True, max_length=255)),
                ('copyright_holder', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='videos', to='media_enhancements.category')),
                ('collection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='wagtailcore.collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
