# Generated by Django 5.2.8 on 2025-12-04 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_enhancements', '0002_audio_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='album_artist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audio',
            name='bitrate',
            field=models.IntegerField(blank=True, help_text='Bitrate in kbps', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='channels',
            field=models.IntegerField(blank=True, help_text='Number of audio channels (1=mono, 2=stereo)', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='codec',
            field=models.CharField(blank=True, help_text='Audio codec (e.g., mp3, aac)', max_length=50),
        ),
        migrations.AddField(
            model_name='audio',
            name='composer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audio',
            name='disc_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='duration_seconds',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='license',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audio',
            name='metadata_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='sample_rate',
            field=models.IntegerField(blank=True, help_text='Sample rate in Hz (e.g., 44100)', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='track_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='waveform_data',
            field=models.JSONField(blank=True, help_text='Waveform data for visualization', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='waveform_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='waveform_image',
            field=models.ImageField(blank=True, help_text='Auto-generated waveform', null=True, upload_to='audio_waveforms/'),
        ),
        migrations.AddField(
            model_name='video',
            name='audio_codec',
            field=models.CharField(blank=True, help_text='Audio codec (e.g., aac)', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='bitrate',
            field=models.IntegerField(blank=True, help_text='Bitrate in kbps', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='cloudfront_url',
            field=models.URLField(blank=True, help_text='CloudFront distribution URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='codec',
            field=models.CharField(blank=True, help_text='Video codec (e.g., h264)', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Auto-generated embed code'),
        ),
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.FloatField(blank=True, help_text='Frames per second', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='remote_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or external video URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 object key', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('local', 'Local Upload'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('external', 'External URL')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'flac', 'aac', 'm4a', 'wma'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])]),
        ),
    ]
