# Generated by Django 5.2.8 on 2025-12-04 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_enhancements', '0003_audio_album_artist_audio_bitrate_audio_channels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tag_type', models.CharField(choices=[('general', 'General'), ('usage', 'Usage Type'), ('style', 'Style'), ('quality', 'Quality'), ('status', 'Status'), ('purpose', 'Purpose')], default='general', max_length=20)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('ai_keywords', models.TextField(blank=True, help_text='Keywords for AI auto-tagging (comma-separated)')),
            ],
            options={
                'verbose_name': 'Predefined Tag',
                'verbose_name_plural': 'Predefined Tags',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom Document', 'verbose_name_plural': 'Custom Documents'},
        ),
        migrations.AddField(
            model_name='category',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Media Types'), ('image', 'Images'), ('video', 'Videos'), ('audio', 'Audio'), ('document', 'Documents')], default='all', help_text='Which media types this category applies to', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('general', 'General'), ('graphics', 'Graphics'), ('audio', 'Audio'), ('docs', 'Documents'), ('icons', 'Icons'), ('banners', 'Banners'), ('logos', 'Logos'), ('photos', 'Photos'), ('illustrations', 'Illustrations'), ('videos', 'Videos'), ('music', 'Music'), ('sfx', 'Sound Effects')], default='general', help_text='Type of category for better organization', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#667eea', help_text='Hex color code for category badge', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-image')", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_enhancements.category'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='Extracted Text'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='is_confidential',
            field=models.BooleanField(default=False, verbose_name='Confidential'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='is_latest_version',
            field=models.BooleanField(default=True, verbose_name='Is Latest Version'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='is_searchable',
            field=models.BooleanField(default=False, verbose_name='Is Searchable'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='language',
            field=models.CharField(blank=True, max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='ocr_language',
            field=models.CharField(default='eng', help_text="Language code for OCR (e.g., 'eng', 'fra', 'deu')", max_length=10, verbose_name='OCR Language'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='ocr_performed',
            field=models.BooleanField(default=False, verbose_name='OCR Performed'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page Count'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='parent_document',
            field=models.ForeignKey(blank=True, help_text='Original document if this is a version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='media_enhancements.customdocument', verbose_name='Parent Document'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='preview_generated',
            field=models.BooleanField(default=False, verbose_name='Preview Generated'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='First page preview', null=True, upload_to='document_previews/', verbose_name='Preview Image'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Requires Approval'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='version_notes',
            field=models.TextField(blank=True, verbose_name='Version Notes'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='version_number',
            field=models.IntegerField(default=1, verbose_name='Version Number'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='word_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Word Count'),
        ),
    ]
