# Generated by Django 5.2.8 on 2025-12-04 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_enhancements', '0004_predefinedtag_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='fa-folder', help_text="Font Awesome icon class (e.g., 'fa-folder')", max_length=50)),
                ('color', models.CharField(blank=True, default='#3b82f6', help_text='Hex color code for folder', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_system_folder', models.BooleanField(default=False, help_text='System folders cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_enhancements.mediafolder')),
            ],
            options={
                'verbose_name': 'Media Folder',
                'verbose_name_plural': 'Media Folders',
                'ordering': ['order', 'name'],
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_files', to='media_enhancements.mediafolder', verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='media_enhancements.mediafolder', verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='customimage',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='media_enhancements.mediafolder', verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='video',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='media_enhancements.mediafolder', verbose_name='Folder'),
        ),
    ]
